- name: Deploy Java App
  hosts: localhost
  tasks:
    - name: Stop and remove old container
      command: docker rm -f java_container
      ignore_errors: yes
      changed_when: false

    - name: Run new container
      command: docker run -d --name java_container javaimg
      args:
        chdir: "/mnt/c/Users/ganes/DevOpsProject"

    - name: Verify container
      command: docker ps --filter name=java_container --format "{% raw %}{{.Status}}{% endraw %}"
      register: container_status
      until: "'Up' in container_status.stdout"
      retries: 5
      delay: 2

    - name: Show logs
      command: docker logs java_container
      register: container_logs
      changed_when: false

    - name: Display output
      debug:
        msg: "Container output: {{ container_logs.stdout_lines }}"
