- name: Deploy Java App on Docker
  hosts: localhost
  tasks:
    - name: Stop existing Docker container
      command: docker stop java_container
      ignore_errors: yes
      
    - name: Remove existing Docker container
      command: docker rm java_container
      ignore_errors: yes
      
    - name: Run new Docker container
      command: docker run --name java_container -d javaimg:latest
      
    - name: Get container logs
      command: docker logs java_container
      register: container_logs
      
    - name: Display container output
      debug:
        msg: "{{ container_logs.stdout_lines }}"